modules_dir = "."
total_memory_limit = "Infinity"

[[module]]
name = "curl_adapter"
logger_enabled = true
  [module.mounted_binaries]
  curl = "/usr/bin/curl"

[[module]]
name = "chain_connector"
logger_enabled = true
