networks:
  nox:
    driver: bridge
    ipam:
      config:
        - subnet: 10.50.10.0/24

services:
  deal-aurora:
    image: ${DEAL_AURORA_IMAGE}
    ports:
      - 8545:8545
    networks:
      nox:

  ipfs:
    image: ipfs/go-ipfs
    ports:
      - 5001:5001
      - 4001:4001
    environment:
      IPFS_PROFILE: server
    volumes:
      - ./ipfs/:/container-init.d/
    networks:
      nox:
        ipv4_address: 10.50.10.100

  nox-1:
    image: ${NOX_IMAGE}
    ports:
      - 7771:7771
      - 9991:9991
    environment:
#      FLUENCE_SYSTEM_SERVICES__AQUA_IPFS__IPFS_BINARY_PATH: "/opt/homebrew/bin/ipfs"
      FLUENCE_SYSTEM_SERVICES__ENABLE: "aqua-ipfs"
      WASM_LOG: "trace"

      FLUENCE_ENV_AQUA_IPFS_EXTERNAL_API_MULTIADDR: "/ip4/10.50.10.100/tcp/5001"
      FLUENCE_ENV_CONNECTOR_API_ENDPOINT: http://deal-aurora:8545
      FLUENCE_ENV_CONNECTOR_CONTRACT_ADDRESS: "0xea6777e8c011E7968605fd012A9Dd49401ec386C"
      FLUENCE_ENV_CONNECTOR_FROM_BLOCK: 0x0
      FLUENCE_ENV_AQUA_IPFS_LOCAL_API_MULTIADDR: "/ip4/10.50.10.100/tcp/5001"
      RUST_LOG: "info,aquamarine=warn,tokio_threadpool=info,tokio_reactor=info,mio=info,tokio_io=info,soketto=info,yamux=info,multistream_select=info,libp2p_secio=info,libp2p_websocket::framed=info,libp2p_ping=info,libp2p_core::upgrade::apply=info,libp2p_kad::kbucket=info,cranelift_codegen=info,wasmer_wasi=info,cranelift_codegen=info,wasmer_wasi=info,run-console=debug"
    command:
      - --aqua-pool-size=2
      - -t=7771
      - -w=9991
      - -x=10.50.10.10
      - --external-maddrs
      - /dns4/nox-1/tcp/7771
      - /dns4/nox-1/tcp/9991/ws
      - --allow-private-ips
      - --local
      # - --bootstraps=/dns/nox-1/tcp/7771
      # 12D3KooWBM3SdXWqGaawQDGQ6JprtwswEg3FWGvGhmgmMez1vRbR
      - -k=hK62afickoeP2uZbmSkAYXxxqP8ozq16VRN7qfTP719EHC5V5tjrtW57BSjUr8GvsEXmJRbtejUWyPZ2rZMyQdq
    depends_on:
      - ipfs
    networks:
      nox:
        ipv4_address: 10.50.10.10

  nox-2:
    image: ${NOX_IMAGE}
    ports:
      - 7772:7772
      - 9992:9992
    environment:
      FLUENCE_SYSTEM_SERVICES__ENABLE: "aqua-ipfs"
      WASM_LOG: "trace"

      FLUENCE_ENV_AQUA_IPFS_EXTERNAL_API_MULTIADDR: "/ip4/10.50.10.100/tcp/5001"
      FLUENCE_ENV_CONNECTOR_API_ENDPOINT: http://deal-aurora:8545
      FLUENCE_ENV_CONNECTOR_CONTRACT_ADDRESS: "0xea6777e8c011E7968605fd012A9Dd49401ec386C"
      FLUENCE_ENV_CONNECTOR_FROM_BLOCK: earliest
      FLUENCE_ENV_AQUA_IPFS_LOCAL_API_MULTIADDR: "/ip4/10.50.10.100/tcp/5001"
      RUST_LOG: "info,aquamarine=warn,tokio_threadpool=info,tokio_reactor=info,mio=info,tokio_io=info,soketto=info,yamux=info,multistream_select=info,libp2p_secio=info,libp2p_websocket::framed=info,libp2p_ping=info,libp2p_core::upgrade::apply=info,libp2p_kad::kbucket=info,cranelift_codegen=info,wasmer_wasi=info,cranelift_codegen=info,wasmer_wasi=info,run-console=debug"
    command:
      - --aqua-pool-size=2
      - -t=7772
      - -w=9992
      - -x=10.50.10.20
      - --external-maddrs
      - /dns4/nox-2/tcp/7772
      - /dns4/nox-2/tcp/9992/ws
      - --allow-private-ips
      - --bootstraps=/dns/nox-1/tcp/7771
      # 12D3KooWQdpukY3p2DhDfUfDgphAqsGu5ZUrmQ4mcHSGrRag6gQK
      - -k=2WijTVdhVRzyZamWjqPx4V4iNMrajegNMwNa2PmvPSZV6RRpo5M2fsPWdQr22HVRubuJhhSw8BrWiGt6FPhFAuXy
    depends_on:
      - ipfs
    networks:
      nox:
        ipv4_address: 10.50.10.20

  nox-3:
    image: ${NOX_IMAGE}
    ports:
      - 7773:7773
      - 9993:9993
    environment:
      FLUENCE_ENV_AQUA_IPFS_EXTERNAL_API_MULTIADDR: "/ip4/10.50.10.100/tcp/5001"
      FLUENCE_ENV_CONNECTOR_API_ENDPOINT: http://deal-aurora:8545
      FLUENCE_ENV_CONNECTOR_CONTRACT_ADDRESS: "0xea6777e8c011E7968605fd012A9Dd49401ec386C"
      FLUENCE_ENV_CONNECTOR_FROM_BLOCK: earliest
      FLUENCE_ENV_AQUA_IPFS_LOCAL_API_MULTIADDR: "/ip4/10.50.10.100/tcp/5001"
      RUST_LOG: "info,aquamarine=warn,tokio_threadpool=info,tokio_reactor=info,mio=info,tokio_io=info,soketto=info,yamux=info,multistream_select=info,libp2p_secio=info,libp2p_websocket::framed=info,libp2p_ping=info,libp2p_core::upgrade::apply=info,libp2p_kad::kbucket=info,cranelift_codegen=info,wasmer_wasi=info,cranelift_codegen=info,wasmer_wasi=info,run-console=debug"
    command:
      - --aqua-pool-size=2
      - -t=7773
      - -w=9993
      - -x=10.50.10.30
      - --external-maddrs
      - /dns4/nox-3/tcp/7773
      - /dns4/nox-3/tcp/9993/ws
      - --allow-private-ips
      - --bootstraps=/dns/nox-1/tcp/7771
      # 12D3KooWRT8V5awYdEZm6aAV9HWweCEbhWd7df4wehqHZXAB7yMZ
      - -k=2n2wBVanBeu2GWtvKBdrYK9DJAocgG3PrTUXMharq6TTfxqTL4sLdXL9BF23n6rsnkAY5pR9vBtx2uWYDQAiZdrX
    depends_on:
      - ipfs
    networks:
      nox:
        ipv4_address: 10.50.10.30
