services:
  ipfs:
    image: ipfs/go-ipfs
    pull_policy: always
    ports:
      - 5001:5001
      - 4001:4001
    environment:
      IPFS_PROFILE: server
    volumes:
      - ./ipfs/:/container-init.d/
