[package]
name = "curl_adapter"
version = "0.5.1"
edition = "2018"
publish = false

[[bin]]
name = "curl_adapter"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = "0.10.0"

[dev-dependencies]
marine-rs-sdk-test = "0.10.0"
