total_memory_limit = "Infinity"

[[module]]
name = "curl_adapter"
load_from = "/home/maar/Fluence/decider/target/wasm32-wasi/release/curl_adapter.wasm"

  [module.mounted_binaries]
  curl = "/usr/bin/curl"

[[module]]
name = "chain_connector"
load_from = "/home/maar/Fluence/decider/target/wasm32-wasi/release/chain_connector.wasm"
