name: "ci"

on:
  pull_request:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"

env:
  FORCE_COLOR: true
  CI: true

jobs:
  decider:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install fluence-cli
        run: npm i -g fluencelabs/cli@unstable

      - name: Create builtin distribution package
        run: ./builtin-package/package.sh

      - name: Calculate SHA256
        id: sha
        run: |
          # Calculate sha256
          du -hs decider.tar.gz
          sha256sum decider.tar.gz
          sha=($(sha256sum decider.tar.gz))
          echo "sha256=${sha}" >> $GITHUB_OUTPUT

      - name: Upload package to checks
        uses: actions/upload-artifact@v3
        with:
          name: decider.tar.gz
          path: decider.tar.gz
