name: "e2e"

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/e2e.yml"
      - "!.github/workflows/snapshot.yml"
    types:
      - "labeled"
      - "synchronize"
      - "opened"
      - "reopened"
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/e2e.yml"
      - "!.github/workflows/snapshot.yml"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  decider:
    if: >
      github.event_name == 'push' ||
      contains(github.event.pull_request.labels.*.name, 'e2e')
    uses: ./.github/workflows/snapshot.yml
    with:
      ref: ${{ github.ref }}

  nox:
    needs:
      - decider

    uses: fluencelabs/nox/.github/workflows/build.yml@master
    with:
      ref: update-to-lightweight-decider
      cargo-dependencies: |
        [
          {
            "package": "decider-distro",
            "version": "=${{ needs.decider.outputs.cargo-version }}",
            "manifest": "crates/system-services/Cargo.toml",
            "registry": "fluence"
          }
        ]

  nox-snapshot:
    name: "nox"
    needs:
      - nox

    uses: fluencelabs/nox/.github/workflows/container.yml@master
    with:
      image-name: "docker.fluence.dev/distro"

  cli:
    needs:
      - nox-snapshot
    uses: fluencelabs/cli/.github/workflows/tests.yml@main
    with:
      nox-image: "${{ needs.nox-snapshot.outputs.nox-image }}"
      ref: change-nox-config
