name: Build snapshot

on:
  workflow_call:
    inputs:
      cargo-dependencies:
        description: "Cargo dependencies map"
        type: string
        default: "null"
      ref:
        description: "git ref to checkout to"
        type: string
        default: "main"
    outputs:
      cargo-version:
        description: "Cargo snapshot version"
        value: ${{ jobs.snapshot.outputs.version }}

env:
  FORCE_COLOR: true
  CI: true

jobs:
  snapshot:
    name: "Build crates"
    runs-on: builder
    timeout-minutes: 60

    outputs:
      version: "${{ steps.snapshot.outputs.version }}"

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3
        with:
          repository: fluencelabs/decider
          ref: ${{ inputs.ref }}

      - name: Setup rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install fluence-cli
        run: npm i -g @fluencelabs/cli@unstable

      - name: Set dependencies
        if: inputs.cargo-dependencies != 'null'
        uses: fluencelabs/github-actions/cargo-set-dependency@main
        with:
          dependencies: ${{ inputs.cargo-dependencies }}
          path: src/distro

      - name: Build distro
        run: ./build.sh

      - name: Import secrets
        uses: hashicorp/vault-action@v2.5.0
        with:
          url: https://vault.fluence.dev
          path: jwt/github
          role: ci
          method: jwt
          jwtGithubAudience: "https://github.com/fluencelabs"
          jwtTtl: 300
          exportToken: false
          secrets: |
            kv/cargo-registry/users/ci token | CARGO_REGISTRIES_FLUENCE_TOKEN

      - name: Generate snapshot version
        id: version
        uses: fluencelabs/github-actions/generate-snapshot-id@main

      - name: Publish crate snapshots
        id: snapshot
        uses: fluencelabs/github-actions/cargo-publish-snapshot@main
        with:
          id: ${{ steps.version.outputs.id }}
          path: src/distro

      - name: Install ipfs
        uses: nahsi/setup-ipfs@v1

      - name: Create builtin distribution package
        run: ./builtin-package/package.sh

      - name: Calculate SHA256
        id: sha
        run: |
          # Calculate sha256
          du -hs connector.tar.gz
          sha256sum connector.tar.gz
          sha=($(sha256sum connector.tar.gz))
          echo "sha256=${sha}" >> $GITHUB_OUTPUT

      - name: Upload package to checks
        uses: actions/upload-artifact@v3
        with:
          name: connector.tar.gz
          path: connector.tar.gz
